# Generated by Django 5.0.6 on 2024-10-30 07:00

from django.db import migrations
from django.utils.text import slugify


def create_initial_categories(apps, schema_editor):
    """
    Creates some initial product categories.
    """
    Category = apps.get_model('store', 'Category')
    categories = [
        "Skincare",
        "Makeup",
        "Haircare",
        "Fragrance",
        "Body Care",
    ]
    for name in categories:
        Category.objects.get_or_create(name=name, defaults={'slug': slugify(name)})


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_categories),
    ]