# Generated by Django 5.2.7 on 2025-10-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_populate_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
